# Generated by Django 4.0.1 on 2022-01-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userauth'),
        ('notation', '0003_alter_notationtable_iduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
