# Generated by Django 4.0.1 on 2022-02-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notationtable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
