# Generated by Django 4.0.1 on 2022-01-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0006_alter_notationtable_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='categoriesTitle', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='notationtable',
            name='categories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='notation.notescategories'),
        ),
    ]
