# Generated by Django 4.0.1 on 2022-01-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='pdb',
            new_name='pdp',
        ),
    ]
