# Generated by Django 4.0.1 on 2022-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_pdb_userauth_pdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='pdp',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
