# Generated by Django 4.0.1 on 2022-01-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userauth_pdp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuth',
        ),
    ]
