# Generated by Django 4.0.1 on 2022-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotationTable',
            fields=[
                ('note', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('idUser', models.IntegerField(blank=True, null=True)),
                ('idNote', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
