# Generated by Django 4.0.1 on 2022-01-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userauth'),
        ('notation', '0002_alter_notationtable_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notationtable',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.userauth'),
        ),
    ]
