# Generated by Django 4.0.1 on 2022-01-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0003_alter_notationtable_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notationtable',
            old_name='idNote',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='notationtable',
            old_name='idUser',
            new_name='user',
        ),
    ]
