# Generated by Django 4.0.1 on 2022-01-24 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_pdb_userauth_pdp'),
        ('notation', '0004_rename_idnote_notationtable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notationtable',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='notationtable',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notationtable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userauth'),
        ),
    ]
