# Generated by Django 4.0.1 on 2022-01-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notation', '0005_alter_notationtable_date_alter_notationtable_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notationtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
