# Generated by Django 4.0.1 on 2022-01-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0007_notescategories_notationtable_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notationtable',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notation.notescategories'),
        ),
        migrations.AlterField(
            model_name='notationtable',
            name='note',
            field=models.IntegerField(),
        ),
    ]
