# Generated by Django 4.0.1 on 2022-01-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notation', '0008_alter_notationtable_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notationtable',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='notationtable',
            name='note',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valeur', models.IntegerField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notation.notescategories')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notation.notationtable')),
            ],
        ),
    ]
